### ISSUE TITLE
Home Intro View Fix Title

### ISSUE THREAD

**Issue by MrTrai** [DataScience-GT/datascience-gt.github.io#16]
Include “Anyone can be a data scientist” somewhere rather than repeating “We are a community of data scientists…”

Have a link to Workshops folder on Drive (in Content folder) to make content public

Data Science at Georgia Tech instead of just Data Science
Preferred: "Data Science @ Georgia Tech" 

You can remove the subtitled "Georgia Institute of Technology" 

Include our slogan somewhere prominent "Data Science with a Focus on the Community" 

Title words are not centered (other than first letter)
I like the old title and subtitle better - Neeraj
Brings more attention to the user, there’s no need to change it

**Comment by giamnguyen** [comment]
@MrTrai 
- Finished at commit: *f9088c9*
~Data Science at Georgia Tech instead of just Data Science~
~Preferred: "Data Science @ Georgia Tech"~
~You can remove the subtitled "Georgia Institute of Technology"~
~Include our slogan somewhere prominent "Data Science with a Focus on the Community"~
