### ISSUE TITLE
Home Intro View Fix What We Do/Who We Are

### ISSUE THREAD

**Issue by MrTrai** [DataScience-GT/datascience-gt.github.io#17]
Add more to the Who we are and What we do, maybe a third line
Who We Are 
We are a community of data scientists that use their skills to better the community
What We Do 
Learn About Workshop

Under what we do: keep cases consistent - either capitalize everything or don’t capitalize anything

**Comment by giamnguyen** [comment]
@MrTrai 
- Finished at commit: *f9088c9*
~Who We Are~
~We are a community of data scientists that use their skills to better the community~
