### ISSUE TITLE
Events Over View - Enhancing

### ISSUE THREAD

**Issue by MrTrai** [DataScience-GT/datascience-gt.github.io#19]
The corner “Data Science @ GT” can’t be seen once you scroll a little
Take out “Free Pizza” and “And have fun!”
“Data Science hands-on Projects” → “
“Organization Board Members” → “Executive Board Members”

**Comment by giamnguyen** [comment]
@MrTrai 
- Finished at commit: *f9088c9*
~Take out “Free Pizza” and “And have fun!”~
~“Data Science hands-on Projects” → “~
~“Organization Board Members” → “Executive Board Members”~
