### ISSUE TITLE
Exec Intro View - Enhancing

### ISSUE THREAD

**Issue by MrTrai** [DataScience-GT/datascience-gt.github.io#20]
Normalize Picture Sizes: 
Dani’s picture is larger than the rest
Perhaps a Max-Height attribute - look at my branch for size-normalized pictures 
Delete will epperson from board
“Director of Marketing”
“Director of Workshops” → “Director of Content”
“Director of Hackathons” → “Director of External Affairs”

**Comment by giamnguyen** [comment]
@MrTrai 
- Finished at commit: *f9088c9*
~Delete will epperson from board~
~“Director of Workshops” → “Director of Content”~
~“Director of Hackathons” → “Director of External Affairs”~
