### ISSUE TITLE
About Us Page - Enhancing

### ISSUE THREAD

**Issue by MrTrai** [DataScience-GT/datascience-gt.github.io#21]
On About page) Last sentence outside of the textbox is hard to read
^fixes itself when you change the window size/black box resizes itself
Change line to “We also host an annual data-science centered hackathon in February called Hacklytics.” ← link hacklytics.io

**Comment by giamnguyen** [comment]
@MrTrai 
- Finished at commit: *f9088c9*
~Change line to “We also host an annual data-science centered hackathon in February called Hacklytics.” ← link hacklytics.io~
